# ----------------------------------------------------------------------------------------
#  Basic dbt_project.yml template
# ----------------------------------------------------------------------------------------
name: "dbt_academy"
version: "1.0.0"

profile: "dbt_academy"

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

log-path: "logs"
packages-install-path: "dbt_packages"
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_academy:
    +enabled: true
    staging:
      +database: "staging"
      +materialized: view

seeds:
  +database: "landing"
  +full_refresh: true
  +enabled: true

# snapshots:
#   +target_schema: "{{ target.schema }}"

# ----------------------------------------------------------------------------------------
# Runtime variables
# Full documentation: https://docs.getdbt.com/docs/configuring-your-project/variables
# ----------------------------------------------------------------------------------------
vars:
  dbt_date:
    "dbt_date:time_zone": "Europe/Brussels"
  dbt_run_start: "YYYYMMDDHH24MISS"

# ----------------------------------------------------------------------------------------
# Miscellaneous parameters
# ----------------------------------------------------------------------------------------
query-comment:
  comment: "run by {{ target.user }}"
  append: true

quoting:
  database: true
  schema: true
  identifier: true

flags:
  use_colors: False
