sources:
  - name: dbt_academy
    database: landing
    tables:
      - name: raw_customers
        columns:
          - name: id
            data_type: varchar(36)
          - name: name
            data_type: varchar(36)
      - name: raw_items
        columns:
          - name: id
            data_type: varchar(36)
          - name: order_id
            data_type: varchar(36)
          - name: sku
            data_type: varchar(7)
      - name: raw_orders
        columns:
          - name: id
            data_type: varchar(36)
          - name: customer
            data_type: varchar(36)
          - name: ordered_at
            data_type: datetime
          - name: store_id
            data_type: varchar(36)
          - name: subtotal
            data_type: numeric(12,4)
          - name: tax_paid
            data_type: numeric(12,4)
          - name: order_total
            data_type: numeric(12,4)
      - name: raw_products
        columns:
          - name: sku
            data_type: varchar(7)
          - name: name
            data_type: varchar(128)
          - name: type
            data_type: varchar(128)
          - name: price
            data_type: int
          - name: descr
            data_type: varchar(4096)
      - name: raw_stores
        columns:
          - name: id
            data_type: varchar(36)
          - name: name
            data_type: varchar(128)
          - name: opened_at
            data_type: datetime
          - name: tax_rate
            data_type: numeric(6,2)
